2020-12-14 21:27:56,102 (11770/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 21:27:56,102 (11770/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-14 21:27:56,108 (11770/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"?\n\n'
2020-12-14 21:32:52,188 (12104/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 21:32:52,189 (12104/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-14 21:32:52,202 (12104/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "u0_a278" does not exist\n\n'
2020-12-14 21:33:05,919 (12144/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 21:33:05,920 (12144/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-14 21:33:05,934 (12144/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "kydemy" does not exist\n\n'
2020-12-14 23:18:48,317 (26003/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 23:18:48,320 (26003/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-14 23:29:38,605 (26745/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 23:29:38,606 (26745/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-14 23:30:12,992 (26989/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-14 23:30:12,992 (26989/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 17:45:34,062 (29237/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 17:45:34,065 (29237/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 17:45:38,911 (29237/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 17:46:14,341 (29282/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 17:46:14,342 (29282/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 17:48:59,786 (29399/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 17:48:59,787 (29399/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 17:49:04,542 (29399/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 17:53:16,046 (29612/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 17:53:16,046 (29612/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 17:53:18,378 (29612/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 22:15:52,832 (15143/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 22:15:52,835 (15143/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 22:15:55,464 (15143/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 22:16:31,624 (15169/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 22:16:31,625 (15169/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 22:16:33,436 (15169/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 22:24:04,188 (16223/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 22:24:04,193 (16223/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-12-22 22:24:10,516 (16223/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/data/data/com.termux/files/usr/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2020-12-22 22:24:17,007 (16236/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2020-12-22 22:24:17,008 (16236/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
